spring:
  application :
    name: career-planning-agent
  ai:
    dashscope:
      api-key: sk-40ea760a6207445da466fa1b7fc0bf62
    mcp:
      client:
        enabled: false

  datasource:
      url: jdbc:postgresql://pgm-uf6tq00m299ay556po.pg.rds.aliyuncs.com/career-planning-agent
      username: my_user
      password: qazwsxedc123A!
#  vectorstore:
#      pgvector:
#          index-type: HNSW
#          dimensions: 1536
#          distance-type: COSINE_DISTANCE
#          max-document-batch-size: 10000


server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.johan\careerplanningagent\controller


# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


#searchAPI
search-api:
  api-key: MGVjC98b1X19bPfMuGVx6PwH